# ============================================================================
# FILE: packages/model_gateway/supportops_model_gateway/providers/hosted.py
#
# THINK OF THIS FILE AS: the only place in the entire project that actually
# talks to a real, paid AI service over the internet.
#
# Everything else deals in the contract from providers/base.py. This file is
# where that contract meets an actual HTTP request to OpenAI's API.
#
# WHY IT IS THE LONGEST FILE IN THE PACKAGE:
#   Almost all of it is defensive. Calling an AI is not like calling a normal
#   API, because the response is generated by a language model and is therefore
#   not guaranteed to be anything in particular. It might be valid JSON. It might
#   be an apology. It might be a refusal. It might be truncated halfway because
#   the token limit was hit.
#
#   So the code is written on the assumption that ANY part of the response may be
#   missing, the wrong type, or nonsense — and every such case must produce a
#   clear error rather than a crash or, worse, a plausible-looking wrong answer.
#
# THE THREE DEFENCES WORTH UNDERSTANDING, all visible below:
#   1. STRUCTURED OUTPUT. The request tells the API "your reply must match this
#      exact JSON shape" (see _build_request_payload). The service enforces it,
#      which removes most malformed-answer problems at source.
#   2. VALIDATION ANYWAY. The reply is checked against the same shape on arrival
#      (_parse_analysis), because trusting the remote enforcement alone would be
#      unwise.
#   3. EVIDENCE CHECKING. The model must cite where its conclusions came from,
#      and _validate_evidence_ids rejects citations of sources that do not exist.
#      This is an anti-hallucination measure, explained at that function.
#
# THE JOURNEY OF ONE CALL:
#   analyze_ticket()
#     -> fetch and fill in the prompt template (packages/prompts/)
#     -> build the request, including the required JSON shape
#     -> POST it, handling timeouts and HTTP errors
#     -> dig the text out of a deeply nested reply
#     -> validate it against the expected shape
#     -> check the evidence citations
#     -> convert to the standard TicketAnalysisResult
# ============================================================================

import json
import time
from typing import Any

import httpx  # the HTTP client library used to make the request
from pydantic import ValidationError

from supportops_model_gateway.errors import (
    ModelProviderConfigurationError,
    ModelProviderRequestError,
    ModelProviderResponseError,
)
from supportops_model_gateway.providers.base import TicketAnalysisInput, TicketAnalysisResult
from supportops_prompts.registry import get_prompt, render_prompt
from supportops_prompts.schemas import FullTicketAnalysis

# --- Names and defaults -----------------------------------------------------
OPENAI_PROVIDER_NAME = "openai"       # the setting value that selects this provider
HOSTED_PROVIDER_ALIAS = "hosted"      # a friendlier alias for the same thing
# Recorded as `source` on every result. Note it includes a VERSION: if this
# integration is ever rewritten against a different API shape, results from the
# old and new versions stay distinguishable in the database forever.
OPENAI_SOURCE = "openai_responses_v1"

DEFAULT_OPENAI_MODEL = "gpt-5.6"
DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1"
DEFAULT_TIMEOUT_SECONDS = 30.0        # give up after 30s, so one slow call cannot block a
                                      # worker or hold a web request open indefinitely
DEFAULT_MAX_OUTPUT_TOKENS = 1200      # caps the reply length, and therefore its cost

FULL_ANALYSIS_PROMPT_NAME = "full_ticket_analysis"
FULL_ANALYSIS_SCHEMA_NAME = "supportops_full_ticket_analysis"

# THE ANTI-HALLUCINATION LIST. The model is required to cite which part of the
# input each conclusion came from, and these four are the only parts that exist.
#
# A model inventing a citation — "according to the customer's account history",
# when no account history was ever supplied — is a strong signal that it is
# making things up. Rejecting the whole response in that case is safer than
# accepting reasoning built on a source that was never there.
ALLOWED_EVIDENCE_IDS = frozenset({
    "ticket-subject",
    "ticket-body",
    "customer-id",
    "policy-context",
})


class HostedTicketAnalysisProvider:
    # Validates its configuration UP FRONT, in the constructor, rather than
    # waiting until a call is attempted.
    #
    # That timing is deliberate. A missing API key discovered at startup is a
    # clear deployment error someone fixes immediately. The same key discovered
    # on the first customer ticket at 2am is an outage. Failing early and loudly
    # is the kinder behaviour.
    def __init__(
        self,
        *,
        api_key: str,
        model_name: str = DEFAULT_OPENAI_MODEL,
        base_url: str = DEFAULT_OPENAI_BASE_URL,
        timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
        max_output_tokens: int = DEFAULT_MAX_OUTPUT_TOKENS,
        # Lets a test inject its own fake HTTP client, so the whole class can be
        # exercised without a network or an API key. See
        # tests/model_gateway/test_ticket_analysis_provider.py.
        http_client: httpx.Client | None = None,
    ) -> None:
        # Each check names the ENVIRONMENT VARIABLE, not the Python parameter.
        # A small kindness with real value: the person reading this error is
        # looking at a deployment configuration, not at this file.
        if not api_key.strip():       # .strip() so a key of only spaces is caught too
            raise ModelProviderConfigurationError(
                "MODEL_API_KEY is required when MODEL_PROVIDER=openai"
            )
        if not model_name.strip():
            raise ModelProviderConfigurationError("MODEL_NAME is required")
        if timeout_seconds <= 0:
            raise ModelProviderConfigurationError("MODEL_TIMEOUT_SECONDS must be greater than 0")
        if max_output_tokens <= 0:
            raise ModelProviderConfigurationError("MODEL_MAX_OUTPUT_TOKENS must be greater than 0")

        self._api_key = api_key
        self._model_name = model_name
        # `.rstrip("/")` removes a trailing slash, so both "https://x/v1" and
        # "https://x/v1/" work. Without it the second would produce a URL with a
        # doubled slash — which some servers tolerate and others reject, making
        # for a genuinely annoying configuration bug.
        self._base_url = base_url.rstrip("/")
        self._timeout_seconds = timeout_seconds
        self._max_output_tokens = max_output_tokens
        self._http_client = http_client or httpx.Client()

    # THE MAIN METHOD — the one required by the contract in providers/base.py.
    def analyze_ticket(self, ticket: TicketAnalysisInput) -> TicketAnalysisResult:
        # STEP 1: fetch the prompt template and fill in this ticket's details.
        # Templates are versioned and live in packages/prompts/ rather than being
        # written inline here, so a prompt can be changed and its version recorded
        # without touching this code.
        prompt_spec = get_prompt(FULL_ANALYSIS_PROMPT_NAME)
        prompt = render_prompt(
            FULL_ANALYSIS_PROMPT_NAME,
            {
                "ticket_subject": ticket.subject,
                "ticket_body": ticket.body,
                # The `or` fallbacks matter: a blank space in the instructions
                # could confuse the model, whereas an explicit "unknown" is
                # unambiguous and gives it something definite to reason about.
                "customer_id": ticket.customer_id or "unknown",
                "policy_context": ticket.policy_context or "No policy context provided.",
            },
        )
        request_payload = self._build_request_payload(
            prompt=prompt,
            prompt_id=prompt_spec.prompt_id,
        )

        # STEP 2: make the call, timing it.
        started = time.perf_counter()
        response_payload = self._post_response(request_payload)
        latency_ms = int((time.perf_counter() - started) * 1000)

        # STEP 3: pull the answer apart and check it. Each of these can raise.
        output_text = _extract_output_text(response_payload)
        analysis = _parse_analysis(output_text)
        usage = _extract_usage(response_payload)
        raw_response_id = _string_or_none(response_payload.get("id"))

        # STEP 4: convert to the standard shape the rest of the app understands.
        return _analysis_to_result(
            analysis=analysis,
            ticket=ticket,
            # Prefers the model name the API REPORTS over the one we requested.
            # Worth doing: asking for a general name can be resolved by the
            # service to a specific dated version, and recording what actually
            # ran is what makes a later quality change explainable.
            model_name=_string_or_none(response_payload.get("model")) or self._model_name,
            prompt_version=prompt_spec.prompt_id,
            input_tokens=usage["input_tokens"],
            output_tokens=usage["output_tokens"],
            latency_ms=latency_ms,
            raw_response_id=raw_response_id,
        )

    # Builds the JSON body of the request.
    #
    # THE MOST IMPORTANT PART IS THE "text" BLOCK AT THE BOTTOM. It is what turns
    # this from "ask a model and hope" into something dependable.
    def _build_request_payload(self, *, prompt: str, prompt_id: str) -> dict[str, Any]:
        return {
            "model": self._model_name,
            "input": prompt,
            "max_output_tokens": self._max_output_tokens,   # caps length, and cost

            # "store": False tells the provider NOT to retain this request on
            # their servers. A privacy decision, and an important one: ticket
            # bodies contain customers' personal data, and the fewer copies of it
            # exist outside our own systems, the better. See docs/threat-model.md.
            "store": False,

            # Labels attached to the call, visible in the provider's own
            # dashboard. Useful when investigating from their side which prompt
            # version produced a particular result.
            "metadata": {
                "prompt_id": prompt_id,
                "schema_name": FULL_ANALYSIS_SCHEMA_NAME,
            },

            # STRUCTURED OUTPUT — the single most valuable line in this file.
            #
            # It hands the provider a formal description of the exact JSON shape
            # the reply must take, generated automatically from the Pydantic model
            # in packages/prompts/schemas.py. `model_json_schema()` does that
            # conversion, which means the definition lives in ONE place and cannot
            # drift between what we ask for and what we validate.
            #
            # "strict": True makes the provider ENFORCE it during generation
            # rather than merely aiming for it. That eliminates the single most
            # common failure mode of LLM integrations — a reply that is prose
            # where JSON was expected, or JSON missing half its fields.
            "text": {
                "format": {
                    "type": "json_schema",
                    "name": FULL_ANALYSIS_SCHEMA_NAME,
                    "strict": True,
                    "schema": FullTicketAnalysis.model_json_schema(),
                }
            },
        }

    # Sends the request and returns the parsed JSON reply.
    #
    # Every failure here becomes one of OUR error types, never an httpx exception.
    # That translation at the boundary is what keeps knowledge of which HTTP
    # library we use from leaking into routes and worker code.
    def _post_response(self, payload: dict[str, Any]) -> dict[str, Any]:
        try:
            response = self._http_client.post(
                f"{self._base_url}/responses",
                headers={
                    # "Bearer" is the standard way to present an API key. Note the
                    # key never appears in any log line or error message in this
                    # file — deliberately, since a leaked key is a serious incident.
                    "Authorization": f"Bearer {self._api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=self._timeout_seconds,
            )
            response.raise_for_status()     # turns a 4xx/5xx reply into an exception

        # Three catches, from most specific to most general. Order matters: a
        # broader catch placed first would swallow the specific ones and lose
        # their detail.
        except httpx.TimeoutException as exc:
            raise ModelProviderRequestError("hosted model request timed out") from exc
        except httpx.HTTPStatusError as exc:
            # The response body is TRUNCATED to 500 characters. Two reasons:
            # error bodies can be enormous, and they sometimes echo back part of
            # the request — which here would mean a customer's ticket text
            # appearing in our logs. Keeping the useful opening and discarding the
            # rest is the right compromise.
            detail = exc.response.text[:500]
            raise ModelProviderRequestError(
                f"hosted model request failed with HTTP {exc.response.status_code}: {detail}"
            ) from exc
        except httpx.HTTPError as exc:
            # The catch-all: DNS failure, connection refused, TLS problems.
            raise ModelProviderRequestError("hosted model request failed") from exc

        # The request succeeded. Now check the reply is actually JSON — note this
        # raises a RESPONSE error, not a request error, because the distinction
        # matters to the caller: we reached them, they simply answered badly.
        try:
            parsed = response.json()
        except json.JSONDecodeError as exc:
            raise ModelProviderResponseError("hosted model returned non-JSON response") from exc
        if not isinstance(parsed, dict):
            # Valid JSON can still be a list or a bare number. Everything below
            # assumes a dictionary, so this is checked rather than assumed.
            raise ModelProviderResponseError("hosted model response must be a JSON object")
        return parsed


# ===========================================================================
# HELPERS — pulling apart the reply
# ===========================================================================


# Digs the model's actual text out of the response.
#
# The reason this is thirty lines rather than one: the reply has a nested,
# variable structure, and several things can be wrong at each level. It works
# through them in order of severity.
def _extract_output_text(payload: dict[str, Any]) -> str:
    # (a) An explicit error object in the reply.
    error = payload.get("error")
    if error:
        raise ModelProviderResponseError(f"hosted model returned error: {error}")

    # (b) An unfinished response. `status` may be absent (fine), or "completed"
    # (fine), or something like "incomplete" — which usually means the token
    # limit was hit mid-answer. Accepting that would mean parsing truncated JSON,
    # so it is refused. `!r` in the message shows the value with quotes, making
    # an empty or odd status visible rather than invisible.
    status = payload.get("status")
    if status not in (None, "completed"):
        raise ModelProviderResponseError(f"hosted model response status was {status!r}")

    # (c) THE EASY PATH. Newer API versions provide a flattened `output_text`
    # field. If it is there and non-empty, take it and stop.
    output_text = payload.get("output_text")
    if isinstance(output_text, str) and output_text.strip():
        return output_text

    # (d) THE FALLBACK. Otherwise the text must be assembled from a nested
    # structure: a list of output items, each holding a list of content parts.
    # The loops below walk that structure defensively, skipping anything that is
    # not the expected type rather than crashing on it.
    texts: list[str] = []
    output = payload.get("output")
    if not isinstance(output, list):
        raise ModelProviderResponseError("hosted model response missing output items")

    for item in output:
        if not isinstance(item, dict):
            continue                       # skip anything unexpected
        content = item.get("content")
        if not isinstance(content, list):
            continue
        for part in content:
            if not isinstance(part, dict):
                continue

            # A REFUSAL — the model declining to answer, usually because it
            # judged the request unsafe. Treated as a distinct failure rather
            # than "no text found", because the two mean completely different
            # things: a refusal is the safety system working, and mislabelling it
            # as a technical fault would hide a genuinely useful signal.
            refusal = part.get("refusal")
            if part.get("type") == "refusal" or isinstance(refusal, str):
                raise ModelProviderResponseError("hosted model refused the request")

            if part.get("type") == "output_text" and isinstance(part.get("text"), str):
                texts.append(part["text"])

    # Joined because a long answer may arrive split across several parts.
    text = "".join(texts).strip()
    if not text:
        raise ModelProviderResponseError("hosted model response did not include output text")
    return text


# Checks the model's text against the expected shape.
#
# DEFENCE IN DEPTH: the request already asked the provider to enforce this shape
# during generation. Validating again on arrival costs almost nothing and guards
# against a provider bug, an API change, or a strict-mode failure. Trusting a
# remote system to have validated on our behalf is not a safe assumption for
# something whose output goes on to be shown to customers.
def _parse_analysis(output_text: str) -> FullTicketAnalysis:
    try:
        analysis = FullTicketAnalysis.model_validate_json(output_text)
    except ValidationError as exc:
        raise ModelProviderResponseError("hosted model returned invalid ticket analysis") from exc
    _validate_evidence_ids(analysis)
    return analysis


# THE ANTI-HALLUCINATION CHECK — conceptually the most interesting function here.
#
# The prompt requires the model to cite, for each conclusion, which part of the
# input it came from. Only four parts were supplied (the list at the top of this
# file). If the model cites anything else, it has invented a source.
#
# Why reject the whole response over it: a fabricated citation is direct evidence
# that the model is confabulating rather than reading. Its other conclusions in
# the same response are then suspect too, even the ones that look reasonable. A
# clean rejection is safer than accepting analysis built partly on things that
# were never there.
#
# The error message lists every unsupported ID, sorted, so the person
# investigating sees the full picture in one go rather than discovering them one
# failure at a time.
def _validate_evidence_ids(analysis: FullTicketAnalysis) -> None:
    # `*` unpacks both lists into one combined list — citations appear at two
    # levels in the response, and both need checking.
    evidence_ids = [
        *analysis.evidence_ids,
        *analysis.extracted_fields.evidence_ids,
    ]
    # The set comprehension removes duplicates; sorted() makes the message stable.
    unsupported = sorted({item for item in evidence_ids if item not in ALLOWED_EVIDENCE_IDS})
    if unsupported:
        raise ModelProviderResponseError(
            "hosted model returned unsupported evidence ids: " + ", ".join(unsupported)
        )


# Reads the token counts from the reply.
#
# Note it NEVER raises. Missing usage information degrades to zeros instead.
# Deliberate, and a genuine judgement call: a successful analysis should not be
# thrown away because the billing figures were absent. The cost report loses one
# data point; the customer still gets their draft reply. Failing here would trade
# something valuable for something merely useful.
def _extract_usage(payload: dict[str, Any]) -> dict[str, int]:
    usage = payload.get("usage")
    if not isinstance(usage, dict):
        return {"input_tokens": 0, "output_tokens": 0}
    return {
        "input_tokens": _int_or_zero(usage.get("input_tokens")),
        "output_tokens": _int_or_zero(usage.get("output_tokens")),
    }


# Converts the validated, provider-specific analysis into the standard result
# shape the rest of the application understands.
#
# This is the boundary. Above this line everything is OpenAI-specific; below it,
# nothing is. Getting this translation right is what allows the rest of the
# codebase to remain unaware of which AI service is in use.
def _analysis_to_result(
    *,
    analysis: FullTicketAnalysis,
    ticket: TicketAnalysisInput,
    model_name: str,
    prompt_version: str,
    input_tokens: int,
    output_tokens: int,
    latency_ms: int,
    raw_response_id: str | None,
) -> TicketAnalysisResult:
    # `model_dump(mode="json")` turns the Pydantic object into a plain dictionary
    # of JSON-safe values — necessary because this ends up in a JSON database
    # column, which cannot hold arbitrary Python objects.
    extracted_fields = analysis.extracted_fields.model_dump(mode="json")
    extracted_fields.update(
        {
            "customer_id": ticket.customer_id,
            "provider": OPENAI_PROVIDER_NAME,
            "evidence_ids": analysis.evidence_ids,    # kept so a reviewer can see what the
                                                      # model claims to have based this on
            "risk_flags": list(analysis.risk_flags),
            # THE ABSTAIN FLAG — small field, significant consequence. The worker
            # in apps/worker/jobs.py reads exactly this key to decide whether to
            # mark the run "abstained" rather than "succeeded". It travels inside
            # this general-purpose dictionary rather than as a dedicated field on
            # TicketAnalysisResult, which is a slightly fragile coupling: renaming
            # this key would silently break that behaviour.
            "abstain": analysis.abstain,
            "raw_response_id": raw_response_id,
            "model_usage": {
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
            },
        }
    )

    # An abstaining model produces no draft reply, so this stays an empty string
    # rather than becoming None — the result type declares a plain `str`, and
    # keeping the type consistent avoids None-checks everywhere downstream.
    suggested_reply = ""
    if analysis.draft_response is not None:
        suggested_reply = analysis.draft_response.response_text

    return TicketAnalysisResult(
        source=OPENAI_SOURCE,
        model_name=model_name,
        prompt_version=prompt_version,
        category=analysis.category,
        priority=analysis.priority,
        requires_escalation=analysis.requires_escalation,
        # Note the mapping: the model reports `category_confidence` specifically,
        # and it is used as the general `confidence`. A small simplification worth
        # being aware of — this number describes confidence in the CATEGORY, not
        # in the draft reply, even though it is presented as an overall figure.
        confidence=analysis.category_confidence,
        summary=_summary_for_analysis(analysis),
        suggested_reply=suggested_reply,
        extracted_fields=extracted_fields,
        reasons=_reasons_for_analysis(analysis),
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        latency_ms=latency_ms,
        raw_response_id=raw_response_id,
    )


# Builds the one-line summary shown to a reviewer.
#
# Constructed from the model's structured fields rather than asking the model for
# a summary sentence. Cheaper (no extra tokens) and more reliable (it cannot be
# phrased oddly), at the cost of being formulaic.
def _summary_for_analysis(analysis: FullTicketAnalysis) -> str:
    if analysis.abstain:
        return "Model abstained because the ticket needs more information."
    return (
        f"Customer ticket classified as {analysis.category} with "
        f"{analysis.priority} priority."
    )


# Builds the list of plain-English reasons a human reviewer reads.
#
# Note it is built up conditionally: the optional lines only appear when they
# have something to say. That keeps a routine analysis short and scannable, while
# a problematic one carries the extra detail — so a longer reasons list is itself
# a signal worth slowing down for.
def _reasons_for_analysis(analysis: FullTicketAnalysis) -> list[str]:
    reasons = [
        "Hosted OpenAI model returned a structured full-ticket analysis.",
        f"Category confidence: {analysis.category_confidence:.2f}.",   # 2 decimal places
    ]
    # "none" is filtered out — it is the model's way of saying "no risks", which
    # would read absurdly as "Risk flags: none."
    risk_flags = [flag for flag in analysis.risk_flags if flag != "none"]
    if risk_flags:
        reasons.append(f"Risk flags: {', '.join(risk_flags)}.")
    # What the model felt it lacked. Genuinely useful to a human, who can often
    # supply exactly that missing piece.
    if analysis.missing_information:
        reasons.append(f"Missing information: {', '.join(analysis.missing_information)}.")
    if analysis.abstain:
        reasons.append("Model abstained from a complete recommendation.")
    return reasons


# --- Two tiny type-safety helpers ------------------------------------------
#
# Both exist because values from an external JSON response cannot be trusted to
# be the type they should be. Converting defensively here means the rest of the
# file can use them without checking.

# Note the quirk: in Python, `True` is an instance of `int`, so a value of `true`
# in the JSON would pass this check and become 1. Harmless for token counts, but
# the kind of detail worth knowing about isinstance checks against int.
def _int_or_zero(value: object) -> int:
    return value if isinstance(value, int) else 0


# Returns None for anything that is not a non-empty string. The `and value` part
# is what turns an empty string into None — so callers can use a single `or`
# fallback rather than checking for both cases.
def _string_or_none(value: object) -> str | None:
    return value if isinstance(value, str) and value else None
